name: Heroku

on:
  push:
    paths:
      - 'bot.py'
      - 'Procfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vaccineitalybot" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_MAIL}}
          dontautocreate: true 
        env:
          HD_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          HD_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          HD_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          HD_S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
          
